    name: sample react ci pipline/workflow

    on:
        push:
            branches:
                - main
                - master

    jobs:
        build-and-test:
            runs-on: ubuntu-latest
                #using github actions               

                #we are going to use github actions insted of saying run we say uses

            steps:
                -   name: setup nodejs

                    uses: actions/setup-node@v6
                     #you can check it is there on git hub actions
                    with:
                     node-version: ''   
                -   name: checknode version 
                    run: node --version
               
            #cloning the project    
                -   name: clone the pipeline
                    uses: actions/checkout@v6 #featch the github repo inside the runner machine
                
                -   name: list directories
                    run: ls
            
                -   name: Install Dependencies
                    run: npm ci

                -   name: list directories
                    run: ls
               
                -   name: run tests
                    run: npm test    
                
                    
                -   name: run builds
                    run: npm run build
                
                -   name: Upload production ready build files
                    uses: actions/upload-artifact@v4
                    with:                    
                        name: build          
                        path: dist             