    name: smaple react ci pipline/workflow

    on:
        push:
            branches:
                - main
                - master

    jobs:
        built-and-test:
            runs-on: ubuntu-latest
                #using github actions               

                #we are going to use github actions insted of saying run we say uses

            steps:
                -   name: setup nodejs

                    uses: actions/setup-node@v6
                     #you can check it is there on git hub actions
                    with:
                     node-version: ''   
                